name: customizable_flashcard
description: A highly customizable flashcard widget.
version: 0.1.0
homepage: https://github.com/oxelf/flutter_customizable_flashcards

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

